In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    'Student_ID': [1,2,3,4,5,6,7,8,9,10],
    'Math': [85, 90, None, 45, 78, 200, 88, 76, None, 95],
    'Science': [80, None, 70, 60, 75, 85, 90, 300, 65, 88],
    'English': [78, 85, 82, None, 74, 89, 91, 87, 76, 95],
    'Attendance': [90, 85, 88, 92, None, 110, 87, 93, 89, 95]
}
df = pd.DataFrame(data)

In [4]:
df

   Student_ID   Math  Science  English  Attendance
0           1   85.0     80.0     78.0        90.0
1           2   90.0      NaN     85.0        85.0
2           3    NaN     70.0     82.0        88.0
3           4   45.0     60.0      NaN        92.0
4           5   78.0     75.0     74.0         NaN
5           6  200.0     85.0     89.0       110.0
6           7   88.0     90.0     91.0        87.0
7           8   76.0    300.0     87.0        93.0
8           9    NaN     65.0     76.0        89.0
9          10   95.0     88.0     95.0        95.0

In [5]:
df.isnull().sum()

Student_ID    0
Math          2
Science       1
English       1
Attendance    1
dtype: int64

In [6]:
df['Math'].fillna(df['Math'].mean(), inplace=True)
df['Science'].fillna(df['Science'].mean(), inplace=True)
df['English'].fillna(df['English'].mean(), inplace=True)
df['Attendance'].fillna(df['Attendance'].mean(), inplace=True)

C:\Users\Om Mishra\AppData\Local\Temp\ipykernel_12468\722913050.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Math'].fillna(df['Math'].mean(), inplace=True)
C:\Users\Om Mishra\AppData\Local\Temp\ipykernel_12468\722913050.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Science'].fillna(df['Science'].mean(), inplace=True)
C:\Users\Om Mishra\AppData\Local\Temp\ipykernel_12468\722913050.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['English'].fillna(df['English'].mean(), inplace=True)
C:\Users\Om Mishra\AppData\Local\Temp\ipykernel_12468\722913050.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Attendance'].fillna(df['Attendance'].mean(), inplace=True)

0     90.000000
1     85.000000
2     88.000000
3     92.000000
4     92.111111
5    110.000000
6     87.000000
7     93.000000
8     89.000000
9     95.000000
Name: Attendance, dtype: float64

In [8]:
df['Math'] = np.where(df['Math'] > 100, df['Math'].mean(), df['Math'])
df['Science'] = np.where(df['Science'] > 100, df['Science'].mean(), df['Science'])
df['Attendance'] = np.where(df['Attendance'] > 100, df['Attendance'].mean(), df['Attendance'])

In [9]:
df

   Student_ID    Math    Science  English  Attendance
0           1  85.000  80.000000     78.0   90.000000
1           2  90.000        NaN     85.0   85.000000
2           3     NaN  70.000000     82.0   88.000000
3           4  45.000  60.000000      NaN   92.000000
4           5  78.000  75.000000     74.0         NaN
5           6  94.625  85.000000     89.0   92.111111
6           7  88.000  90.000000     91.0   87.000000
7           8  76.000  79.382716     87.0   93.000000
8           9     NaN  65.000000     76.0   89.000000
9          10  95.000  88.000000     95.0   95.000000

In [10]:
Q1 = df[['Math','Science','English','Attendance']].quantile(0.25)
Q3 = df[['Math','Science','English','Attendance']].quantile(0.75)
IQR = Q3 - Q1

In [11]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = ((df[['Math','Science','English','Attendance']] < lower_bound) | 
            (df[['Math','Science','English','Attendance']] > upper_bound))

In [12]:
outliers

    Math  Science  English  Attendance
0  False    False    False       False
1  False    False    False       False
2  False    False    False       False
3   True    False    False       False
4  False    False    False       False
5  False    False    False       False
6  False    False    False       False
7  False    False    False       False
8  False    False    False       False
9  False    False    False       False

In [13]:
outliers.sum()

Math          1
Science       0
English       0
Attendance    0
dtype: int64

In [17]:
df[['Math','Science','English','Attendance']] = df[['Math','Science','English','Attendance']].clip(
    lower=lower_bound, 
    upper=upper_bound, 
    axis=1
)

In [18]:
df

   Student_ID       Math    Science  English  Attendance
0           1  85.000000  80.000000     78.0   90.000000
1           2  90.000000        NaN     85.0   85.000000
2           3        NaN  70.000000     82.0   88.000000
3           4  57.015625  60.000000      NaN   92.000000
4           5  78.000000  75.000000     74.0         NaN
5           6  94.625000  85.000000     89.0   92.111111
6           7  88.000000  90.000000     91.0   87.000000
7           8  76.000000  79.382716     87.0   93.000000
8           9        NaN  65.000000     76.0   89.000000
9          10  95.000000  88.000000     95.0   95.000000

In [19]:
df['Math_percent'] = df['Math'] / 100
df[['Math', 'Math_percent']]

        Math  Math_percent
0  85.000000      0.850000
1  90.000000      0.900000
2        NaN           NaN
3  57.015625      0.570156
4  78.000000      0.780000
5  94.625000      0.946250
6  88.000000      0.880000
7  76.000000      0.760000
8        NaN           NaN
9  95.000000      0.950000

In [20]:
df['Science_percent'] = df['Science'] / 100
df[['Science', 'Science_percent']]

     Science  Science_percent
0  80.000000         0.800000
1        NaN              NaN
2  70.000000         0.700000
3  60.000000         0.600000
4  75.000000         0.750000
5  85.000000         0.850000
6  90.000000         0.900000
7  79.382716         0.793827
8  65.000000         0.650000
9  88.000000         0.880000

In [21]:
df.head()

,Student_ID,Math,Science,English,Attendance,Math_percent,Science_percent
0,1,85.000000,80.0,78.0,90.0,0.850000,0.80
1,2,90.000000,NaN,85.0,85.0,0.900000,NaN
2,3,NaN,70.0,82.0,88.0,NaN,0.70
3,4,57.015625,60.0,NaN,92.0,0.570156,0.60
4,5,78.000000,75.0,74.0,NaN,0.780000,0.75